name: black-autolint

on: [push, pull_request]
jobs:
  lint:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        jupyter: true
        with:
          black_args: ". --check"
